#
# For default substitutions, see
# https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values?hl=ja
#
# COMMIT_SHA, see
# https://cloud.google.com/run/docs/continuous-deployment-with-cloud-build?hl=ja
#

steps:

# decrypt
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'kms', 'decrypt', '--ciphertext-file=server/gcp/mqttkey.enc', '--plaintext-file=server/gcp/mqttkey', '--location=global', '--keyring=ambdev', '--key=ambdevkey']

# build docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/ambserver:$COMMIT_SHA', '-f', 'server/gcp/Dockerfile', './server/gcp']
  timeout: 500s
#docker build --no-cache -t ${docker_image_path} .

# decrypt environment variable
#- name: gcr.io/$PROJECT_ID/env
#  args:
#  secretEnv: ['WORD']

# push docker image to registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/$PROJECT_ID/ambserver:$COMMIT_SHA']
#docker push ${storage_region}/${project_id}/${image_name}

# deploy to container
#- name: 'gcr.io/cloud-builders/kubectl'
#  args:  ['apply', '-f', './deployment.yaml', '--record']
#  env:
#  - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a'
#  - 'CLOUDSDK_CONTAINER_CLUSTER=sokui'

#- name: 'gcr.io/cloud-builders/gke-deploy:stable'
#  args:
# - run
#  - --filename=deployment.yaml
#  - --image=asia.gcr.io/uavclouddev/ambserver:latest
#  - --location=asia-northeast1-a
#  - --cluster=

#- name: 'gcr.io/cloud-builders/kubectl'
#  args: ['rollout' ,'history', 'deployment/gnsspos']


#secrets:
#   - kmsKeyName: projects/$PROJECT_ID/locations/global/keyRings/ambdev/cryptoKeys/ambdevkey
#    secretEnv:
#      HELLO_WORLD: CiQASRI0yFRhMxXqaUJsiGpYIgxeKdwYlvuQKWialmq2e6gIeCoSRAC5dgXS7GQoZXAZb8mM1PrRjppbe3ChfrtGXk0ytxaS3Fir3v7dQNNn6wUH1dm4PDebLi7WMAITpay2myZ/HGbmRSyq
